//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaaSDAL
{
    using System;
    using System.Collections.Generic;

    public partial class User
    {
        public User()
        {
            this.Logins = new HashSet<Login>();
        }

        public int Id { get; set; }

        public string FirstName { get; set; }

        public string LastName { get; set; }

        public string MiddleName { get; set; }

        public string Address { get; set; }

        public string Email { get; set; }

        public Nullable<System.DateTime> DOB { get; set; }

        public Nullable<bool> Active { get; set; }

        public Nullable<int> NHGNumber { get; set; }

        public string Gender { get; set; }

        public string Notes { get; set; }

        public Nullable<long> Phone { get; set; }

        public Nullable<long> Mobile { get; set; }

        public Nullable<System.DateTime> CreatedDtm { get; set; }

        public string CreatedBy { get; set; }

        public string UpdatedDtm { get; set; }

        public string UpdatedBy { get; set; }

        public virtual ICollection<Login> Logins { get; set; }

    }
}