//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaaSDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserSubscriptions
    {
        public long UserSubID { get; set; }
        public long UserID { get; set; }
        public int ServiceID { get; set; }
        public short PlanTypeID { get; set; }
        public decimal Amount { get; set; }
        public System.DateTime SubscribedOn { get; set; }
        public System.DateTime ExpiredOn { get; set; }
    
        public virtual ServicePlanTypes ServicePlanTypes { get; set; }
        public virtual Services Services { get; set; }
        public virtual UserInfo UserInfo { get; set; }
    }
}
